[package]
name = "kernel"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
edition = "2018"

[dependencies]
tock-registers = { path = "../libraries/tock-register-interface" }
tock-cells = { path = "../libraries/tock-cells" }
cortex-m-semihosting = "0.3.3"